---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown

version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2.0.2

workflows:
  kitchen:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery

      # Test Kitchen
      - kitchen/dokken-single:
          suite: global
          name: global-debian-9
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          suite: global
          name: global-debian-10
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          suite: global
          name: global-centos-6
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          suite: global
          name: global-centos-7
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          suite: global
          name: global-ubuntu-1604
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          suite: global
          name: global-ubuntu-1804
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          suite: global
          name: global-opensuse-leap
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: system-install
          suite: system-install
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: user-install
          suite: user-install
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: gem
          suite: gem
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: ruby-uninstall
          suite: ruby-uninstall
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: custom-group
          suite: custom-group-install
          requires:
            *lint_and_unit
